### ISSUE TITLE
Links to issues contain full id token, not just id

### ISSUE THREAD

**Issue by karanagai** [Deroin/teamcity-gitlab-issues#1]
While ids are being parsed correctly for the sake of showing the pop-up window, the ones used in actual links to GitLab contain full sub-string that matches the regexp from config.

E.g. if the regexp is ISSUE#(\d+), it produces the URL like: https://GitLabHost/owner/repo/issues/ISSUE#123 
instead of
https://GitLabHost/owner/repo/issues/123 

This is possibly caused by GitLabIssueFetcher.getUrl(...) implementation.

**Comment by ghost** [comment]
You're right, a call to `GitLabIssueFetcher.getIssueId()` is missing. I will fix this on the weekend.

**Comment by ghost** [comment]
@karanagai The issue is fixed, feel free to build a new version of the plugin. An official release will come soon.
